# Generated by Django 2.1.7 on 2020-04-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='images/user_default.png', upload_to='image/%Y%m'),
        ),
    ]
