# Generated by Django 2.1.7 on 2020-04-20 18:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='部门或学院名称')),
                ('desc', models.TextField(verbose_name='部门描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '课程部门',
                'verbose_name_plural': '课程部门',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='教师姓名')),
                ('desc', models.TextField(verbose_name='教师简介')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseDep', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
    ]
