# Generated by Django 2.1.7 on 2020-04-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedep',
            name='image',
            field=models.ImageField(default='/static/images/course.jpg', upload_to='dep/%Y%m', verbose_name='logo'),
        ),
    ]
