# Generated by Django 2.1.7 on 2020-04-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_coursedep_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedep',
            name='course_nums',
            field=models.IntegerField(default=0, verbose_name='课程数'),
        ),
        migrations.AddField(
            model_name='coursedep',
            name='students',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
