# Generated by Django 2.1.7 on 2020-04-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20200422_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='/static/images/mayun.png', upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
