# Generated by Django 2.1.7 on 2020-04-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedep',
            name='image',
            field=models.ImageField(default='images/course.jpg', upload_to='dep/%Y%m', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='images/mayun.png', upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
