# Generated by Django 2.1.7 on 2020-06-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_learningpro_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpro',
            name='container',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='容器id'),
        ),
    ]
