# Generated by Django 2.1.7 on 2020-06-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20200608_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpro',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='容器链接是否有效'),
        ),
    ]
