# Generated by Django 2.1.7 on 2020-04-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='/static/images/course.jpg', upload_to='courses/%Y/%m', verbose_name='封面图'),
        ),
    ]
