# Generated by Django 2.1.7 on 2020-04-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docimage',
            name='remote_url',
            field=models.URLField(default='', verbose_name='镜像地址'),
        ),
    ]
