# Generated by Django 2.1.7 on 2020-04-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200425_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docimage',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='docImageName',
            field=models.CharField(default='', max_length=100, verbose_name='镜像名'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='remote_url',
            field=models.URLField(default='', verbose_name='镜像地址'),
        ),
        migrations.DeleteModel(
            name='DocImage',
        ),
    ]
