# Generated by Django 2.1.7 on 2020-04-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200426_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='remote_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='镜像地址'),
        ),
    ]
