# Generated by Django 2.1.7 on 2020-06-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200426_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='remote_url',
            field=models.CharField(default='', max_length=200, verbose_name='镜像地址'),
        ),
    ]
